# FTEmulator - FTEmulator is a high-performance stock market investment simulator designed with extreme technical efficiency
# Copyright (C) 2025-2025 Álex Frías (alexwebdev05)
# Licensed under AGPL-3.0 - see LICENSE file
# Commercial licensing: alexwebdev05@proton.me | GitHub: https://github.com/alexwebdev05
apiVersion: batch/v1
kind: Job
metadata:
  name: website-update-job-6f19a00
  namespace: website
spec:
  ttlSecondsAfterFinished: 200
  backoffLimit: 4
  template:
    spec:
      restartPolicy: OnFailure
      initContainers:
        - name: git-clone
          image: alpine/git:2.49.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              rm -rf /repo/*
              mkdir -p /repo
              cd /repo
              git clone --depth 1 https://github.com/FTEmulator/website .
          volumeMounts:
            - name: repo-volume
              mountPath: /repo
      containers:
        - name: sync
          image: node:20-alpine
          command: ["/bin/sh", "-c"]
          args:
            - |
              cd /repo
              npm install
              npx next build
              rm -rf /mnt/website/*
              cp -r out/* /mnt/website
              chown -R www-data:www-data /mnt/website
              echo "La pagina se actualizo correctamente"
          volumeMounts:
            - name: website-volume
              mountPath: /mnt/website
            - name: repo-volume
              mountPath: /repo
      volumes:
        - name: website-volume
          persistentVolumeClaim:
            claimName: nginx-pvc
        - name: repo-volume
          emptyDir: {}